"""Schema primitives: a doc_type and the fields that make up its schema.

A doc_type is a *concept* the brain maintains (product, issue, customer, service,
runbook, ...). It is deliberately domain-agnostic — nothing here assumes
infrastructure. The schema drives three things:

    * validation of entities written into the brain,
    * how each field is searched (which fields are indexed, and how strongly), and
    * how entities of the type are drawn on the map (label + color).
"""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field, field_validator

# The data type of a field's value.
FieldType = Literal["string", "text", "number", "boolean", "timestamp"]

# How the field is processed for indexing. `keyword` = exact/filter, `text` =
# tokenized full-text, `timestamp` = date. Mirrors the processing-type idea from
# the reference index (index_metadata.py) without its infra-specific analyzers.
Processing = Literal["keyword", "text", "timestamp"]

# The kind of search enabled on the field. `syntactic` = keyword/full-text (what
# SQLite FTS5 backs today); `semantic` is declarable now and keyword-backed until
# a vector backend lands. `none` excludes the field from the search index.
SearchKind = Literal["syntactic", "semantic", "none"]

# Where a doc_type's entities live / what is their source of truth:
#   "index" — the search DB is the source of truth. Entities are NOT written to
#             files; regenerated by connectors/agents. The default — right for
#             machine-generated, high-volume, or temporal data (they'd drown git).
#   "file"  — JSON files under entities/<doc_type>/ are the source of truth,
#             git-tracked and PR-reviewable. Right for curated, human/agent-authored
#             entities you want to version.
StoragePolicy = Literal["index", "file"]


class FieldSpec(BaseModel):
    """A single field in a doc_type's schema."""

    name: str
    type: FieldType = "string"
    processing: Processing = "keyword"
    search: SearchKind = "syntactic"
    # Relative importance of this field in ranking, mirroring OpenSearch field
    # boosts (`field^10`) in the reference. Higher = curated/high-signal fields
    # rank first. 1.0 is the neutral default.
    boost: float = 1.0
    required: bool = False
    description: Optional[str] = None

    @field_validator("boost")
    @classmethod
    def _positive_boost(cls, v: float) -> float:
        if v <= 0:
            raise ValueError("boost must be > 0")
        return v


class RelationshipSpec(BaseModel):
    """A relationship kind this doc_type is expected to use.

    Declaring relationships makes correlations first-class and discoverable
    instead of improvised free text: the map legend, the navigation guide, and
    an authoring agent all learn the vocabulary a doc_type uses, and edges can be
    lightly validated (right target type). Entities may still use undeclared
    meanings — declaring just names the *expected* ones.
    """

    # The relationship_edge_meaning this describes, e.g. "is monitored by".
    name: str
    # The doc_type this relationship is expected to point at (optional).
    target_doc_type: Optional[str] = None
    description: Optional[str] = None


class DocTypeDisplay(BaseModel):
    """How entities of this doc_type appear on the map."""

    # Which field to use as the human-facing node label. Defaults to `name`.
    label_field: str = "name"
    # Hex color for nodes of this type. Domain-agnostic: colors come from config,
    # not a hardcoded infra palette.
    color: str = "#6b7280"


class DocType(BaseModel):
    """A concept the brain maintains, plus its schema and display settings."""

    doc_type: str
    description: str = ""
    # Source of truth for this type's entities. Defaults to "index" (DB) — set
    # "file" for curated entities you want tracked as JSON in git.
    storage: StoragePolicy = "index"
    display: DocTypeDisplay = Field(default_factory=DocTypeDisplay)
    fields: list[FieldSpec] = Field(default_factory=list)
    # The relationship kinds entities of this type are expected to use.
    relationships: list[RelationshipSpec] = Field(default_factory=list)

    @field_validator("fields")
    @classmethod
    def _unique_field_names(cls, v: list[FieldSpec]) -> list[FieldSpec]:
        names = [f.name for f in v]
        dupes = {n for n in names if names.count(n) > 1}
        if dupes:
            raise ValueError(f"duplicate field names in schema: {sorted(dupes)}")
        return v

    def field(self, name: str) -> Optional[FieldSpec]:
        for f in self.fields:
            if f.name == name:
                return f
        return None

    def relationship(self, name: str) -> Optional[RelationshipSpec]:
        for r in self.relationships:
            if r.name == name:
                return r
        return None

    @classmethod
    def from_dict(cls, data: dict) -> "DocType":
        """Load from a doc_type YAML file's parsed dict.

        Accepts both the flat shape and the nested `schema: { fields: [...] }`
        shape used in the example files.
        """
        data = dict(data)
        schema = data.pop("schema", None)
        if schema and "fields" in schema and "fields" not in data:
            data["fields"] = schema["fields"]
        return cls.model_validate(data)

    def validate_entity_fields(self, values: dict) -> list[str]:
        """Return a list of human-readable validation errors (empty == valid)."""
        errors: list[str] = []
        for f in self.fields:
            if f.required and values.get(f.name) in (None, ""):
                errors.append(f"missing required field '{f.name}'")
        return errors
